services:
    app:
        build:
            context: .
            args:
                - VITE_NOTIFICATIONS_API_URL=${VITE_NOTIFICATIONS_API_URL}
        ports:
            - '5173:5173'
        environment:
            - PRIVATE_KEY=${PRIVATE_KEY}
            - GROQ_API_KEY=${GROQ_API_KEY}
            - DATABASE_URL=${DATABASE_URL}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
            - YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
            - SESSION_SECRET=${SESSION_SECRET}
            - ONLINE_SECRET=${ONLINE_SECRET:-}
            - BOT_DATABASE=${BOT_DATABASE}
            - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - YSTU_TOKENS_SECRET=${YSTU_TOKENS_SECRET}
        restart: unless-stopped
        networks:
            - ysturasp-db
            - proxy
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.ysturasp-main.rule=PathPrefix(`/`)'
            - 'traefik.http.routers.ysturasp-main.entrypoints=web'
            - 'traefik.http.routers.ysturasp-main.priority=10'
            - 'traefik.http.services.ysturasp-main.loadbalancer.server.port=5173'

networks:
    ysturasp-db:
        external: true
    proxy:
        external: true
